<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8"/>
    <title>New project</title>
    <link href="assets/style.css" rel="stylesheet" type="text/css"/></head>
  <body onLoad="init()">
    <script>/* This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this file,
 * You can obtain one at http://mozilla.org/MPL/2.0/. */


function toArray(iter) {
    if (iter === null) {
        return null;
    }
    return Array.prototype.slice.call(iter);
}

function find(selector, elem) { // eslint-disable-line no-redeclare
    if (!elem) {
        elem = document;
    }
    return elem.querySelector(selector);
}

function findAll(selector, elem) {
    if (!elem) {
        elem = document;
    }
    return toArray(elem.querySelectorAll(selector));
}

function sortColumn(elem) {
    toggleSortStates(elem);
    const colIndex = toArray(elem.parentNode.childNodes).indexOf(elem);
    let key;
    if (elem.classList.contains('result')) {
        key = keyResult;
    } else if (elem.classList.contains('links')) {
        key = keyLink;
    } else {
        key = keyAlpha;
    }
    sortTable(elem, key(colIndex));
}

function showAllExtras() { // eslint-disable-line no-unused-vars
    findAll('.col-result').forEach(showExtras);
}

function hideAllExtras() { // eslint-disable-line no-unused-vars
    findAll('.col-result').forEach(hideExtras);
}

function showExtras(colresultElem) {
    const extras = colresultElem.parentNode.nextElementSibling;
    const expandcollapse = colresultElem.firstElementChild;
    extras.classList.remove('collapsed');
    expandcollapse.classList.remove('expander');
    expandcollapse.classList.add('collapser');
}

function hideExtras(colresultElem) {
    const extras = colresultElem.parentNode.nextElementSibling;
    const expandcollapse = colresultElem.firstElementChild;
    extras.classList.add('collapsed');
    expandcollapse.classList.remove('collapser');
    expandcollapse.classList.add('expander');
}

function showFilters() {
    let visibleString = getQueryParameter('visible') || 'all';
    visibleString = visibleString.toLowerCase();
    const checkedItems = visibleString.split(',');

    const filterItems = document.getElementsByClassName('filter');
    for (let i = 0; i < filterItems.length; i++) {
        filterItems[i].hidden = false;

        if (visibleString != 'all') {
            filterItems[i].checked = checkedItems.includes(filterItems[i].getAttribute('data-test-result'));
            filterTable(filterItems[i]);
        }
    }
}

function addCollapse() {
    // Add links for show/hide all
    const resulttable = find('table#results-table');
    const showhideall = document.createElement('p');
    showhideall.innerHTML = '<a href="javascript:showAllExtras()">Show all details</a> / ' +
                            '<a href="javascript:hideAllExtras()">Hide all details</a>';
    resulttable.parentElement.insertBefore(showhideall, resulttable);

    // Add show/hide link to each result
    findAll('.col-result').forEach(function(elem) {
        const collapsed = getQueryParameter('collapsed') || 'Passed';
        const extras = elem.parentNode.nextElementSibling;
        const expandcollapse = document.createElement('span');
        if (extras.classList.contains('collapsed')) {
            expandcollapse.classList.add('expander');
        } else if (collapsed.includes(elem.innerHTML)) {
            extras.classList.add('collapsed');
            expandcollapse.classList.add('expander');
        } else {
            expandcollapse.classList.add('collapser');
        }
        elem.appendChild(expandcollapse);

        elem.addEventListener('click', function(event) {
            if (event.currentTarget.parentNode.nextElementSibling.classList.contains('collapsed')) {
                showExtras(event.currentTarget);
            } else {
                hideExtras(event.currentTarget);
            }
        });
    });
}

function getQueryParameter(name) {
    const match = RegExp('[?&]' + name + '=([^&]*)').exec(window.location.search);
    return match && decodeURIComponent(match[1].replace(/\+/g, ' '));
}

function init () { // eslint-disable-line no-unused-vars
    resetSortHeaders();

    addCollapse();

    showFilters();

    sortColumn(find('.initial-sort'));

    findAll('.sortable').forEach(function(elem) {
        elem.addEventListener('click',
            function() {
                sortColumn(elem);
            }, false);
    });
}

function sortTable(clicked, keyFunc) {
    const rows = findAll('.results-table-row');
    const reversed = !clicked.classList.contains('asc');
    const sortedRows = sort(rows, keyFunc, reversed);
    /* Whole table is removed here because browsers acts much slower
     * when appending existing elements.
     */
    const thead = document.getElementById('results-table-head');
    document.getElementById('results-table').remove();
    const parent = document.createElement('table');
    parent.id = 'results-table';
    parent.appendChild(thead);
    sortedRows.forEach(function(elem) {
        parent.appendChild(elem);
    });
    document.getElementsByTagName('BODY')[0].appendChild(parent);
}

function sort(items, keyFunc, reversed) {
    const sortArray = items.map(function(item, i) {
        return [keyFunc(item), i];
    });

    sortArray.sort(function(a, b) {
        const keyA = a[0];
        const keyB = b[0];

        if (keyA == keyB) return 0;

        if (reversed) {
            return keyA < keyB ? 1 : -1;
        } else {
            return keyA > keyB ? 1 : -1;
        }
    });

    return sortArray.map(function(item) {
        const index = item[1];
        return items[index];
    });
}

function keyAlpha(colIndex) {
    return function(elem) {
        return elem.childNodes[1].childNodes[colIndex].firstChild.data.toLowerCase();
    };
}

function keyLink(colIndex) {
    return function(elem) {
        const dataCell = elem.childNodes[1].childNodes[colIndex].firstChild;
        return dataCell == null ? '' : dataCell.innerText.toLowerCase();
    };
}

function keyResult(colIndex) {
    return function(elem) {
        const strings = ['Error', 'Failed', 'Rerun', 'XFailed', 'XPassed',
            'Skipped', 'Passed'];
        return strings.indexOf(elem.childNodes[1].childNodes[colIndex].firstChild.data);
    };
}

function resetSortHeaders() {
    findAll('.sort-icon').forEach(function(elem) {
        elem.parentNode.removeChild(elem);
    });
    findAll('.sortable').forEach(function(elem) {
        const icon = document.createElement('div');
        icon.className = 'sort-icon';
        icon.textContent = 'vvv';
        elem.insertBefore(icon, elem.firstChild);
        elem.classList.remove('desc', 'active');
        elem.classList.add('asc', 'inactive');
    });
}

function toggleSortStates(elem) {
    //if active, toggle between asc and desc
    if (elem.classList.contains('active')) {
        elem.classList.toggle('asc');
        elem.classList.toggle('desc');
    }

    //if inactive, reset all other functions and add ascending active
    if (elem.classList.contains('inactive')) {
        resetSortHeaders();
        elem.classList.remove('inactive');
        elem.classList.add('active');
    }
}

function isAllRowsHidden(value) {
    return value.hidden == false;
}

function filterTable(elem) { // eslint-disable-line no-unused-vars
    const outcomeAtt = 'data-test-result';
    const outcome = elem.getAttribute(outcomeAtt);
    const classOutcome = outcome + ' results-table-row';
    const outcomeRows = document.getElementsByClassName(classOutcome);

    for(let i = 0; i < outcomeRows.length; i++){
        outcomeRows[i].hidden = !elem.checked;
    }

    const rows = findAll('.results-table-row').filter(isAllRowsHidden);
    const allRowsHidden = rows.length == 0 ? true : false;
    const notFoundMessage = document.getElementById('not-found-message');
    notFoundMessage.hidden = !allRowsHidden;
}
</script>
    <h1>New project</h1>
    <p>Report generated on 18-Jan-2023 at 19:21:06 by <a href="https://pypi.python.org/pypi/pytest-html">pytest-html</a> v3.2.0</p>
    <h2>Environment</h2>
    <table id="environment">
      <tr>
        <td>Packages</td>
        <td>{"pluggy": "1.0.0", "pytest": "7.2.1"}</td></tr>
      <tr>
        <td>Platform</td>
        <td>macOS-10.15.7-x86_64-i386-64bit</td></tr>
      <tr>
        <td>Plugins</td>
        <td>{"html": "3.2.0", "metadata": "2.0.4"}</td></tr>
      <tr>
        <td>Python</td>
        <td>3.11.1</td></tr></table>
    <h2>Summary</h2>
    <p>2 tests ran in 67.05 seconds. </p>
    <p class="filter" hidden="true">(Un)check the boxes to filter the results.</p><input checked="true" class="filter" data-test-result="passed" disabled="true" hidden="true" name="filter_checkbox" onChange="filterTable(this)" type="checkbox"/><span class="passed">0 passed</span>, <input checked="true" class="filter" data-test-result="skipped" disabled="true" hidden="true" name="filter_checkbox" onChange="filterTable(this)" type="checkbox"/><span class="skipped">0 skipped</span>, <input checked="true" class="filter" data-test-result="failed" hidden="true" name="filter_checkbox" onChange="filterTable(this)" type="checkbox"/><span class="failed">2 failed</span>, <input checked="true" class="filter" data-test-result="error" disabled="true" hidden="true" name="filter_checkbox" onChange="filterTable(this)" type="checkbox"/><span class="error">0 errors</span>, <input checked="true" class="filter" data-test-result="xfailed" disabled="true" hidden="true" name="filter_checkbox" onChange="filterTable(this)" type="checkbox"/><span class="xfailed">0 expected failures</span>, <input checked="true" class="filter" data-test-result="xpassed" disabled="true" hidden="true" name="filter_checkbox" onChange="filterTable(this)" type="checkbox"/><span class="xpassed">0 unexpected passes</span>
    <h2>Results</h2>
    <table id="results-table">
      <thead id="results-table-head">
        <tr>
          <th class="sortable result initial-sort" col="result">Result</th>
          <th class="sortable" col="name">Test</th>
          <th class="sortable" col="duration">Duration</th>
          <th class="sortable links" col="links">Links</th></tr>
        <tr hidden="true" id="not-found-message">
          <th colspan="4">No results found. Try to check the filters</th></tr></thead>
      <tbody class="failed results-table-row">
        <tr>
          <td class="col-result">Failed</td>
          <td class="col-name">testcases/test_case1.py::TestOne::test_search_trip_1_test1</td>
          <td class="col-duration">42.40</td>
          <td class="col-links"><a class="url" href="https://www.yatra.com/" target="_blank">URL</a> </td></tr>
        <tr>
          <td class="extra" colspan="4">
            <div><div><img src="testcases/test_case1.py_TestOne_test_search_trip_1_test1.png" alt="screenshot" style="width:300px;height=200px"onclick="window.open(this.src)" align="right"/></div></div>
            <div class="log">self = &lt;testcases.test_case1.TestOne testMethod=test_search_trip_1_test1&gt;, going_from = &#x27;MEL&#x27;, going_to = &#x27;JFK&#x27;, auto_going_to = &#x27;JFK&#x27;, date = &#x27;23/01/2023&#x27;<br/><br/>    @file_data(&quot;/Users/evgen/PycharmProjects/Selenium/testdata/testdata.json&quot;)<br/>    def test_search_trip(self, going_from, going_to, auto_going_to, date):<br/>        search_result = self.l.search_flights(going_from, going_to, auto_going_to, date)<br/>        time.sleep(2)<br/>        self.l.page_scroll()<br/>        time.sleep(3)<br/>        search_result.click_filter_flights()<br/>        self.log.info(&quot;Select 1 Stop&quot;)<br/>&gt;       self.ut.assert_item_in_list(search_result.get_all_element_one_stop(), &quot;1 Stop&quot;)<br/><br/>testcases/test_case1.py:32: <br/>_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ <br/>utilitize/utils.py:13: in assert_item_in_list<br/>    self.assert_all()<br/>venv/lib/python3.11/site-packages/softest/case.py:139: in assert_all<br/>    self.fail(&#x27;&#x27;.join(failure_output))<br/><span class="error">E   AssertionError: ++++ soft assert failure details follow below ++++</span><br/><span class="error">E   </span><br/><span class="error">E   ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++</span><br/><span class="error">E   The following 35 failures were found in &quot;wrapper&quot; (utilitize.utils.Utilz):</span><br/><span class="error">E   +----------------------+----------------------+----------------------+</span><br/><span class="error">E    Failure 1 (&quot;wrapper&quot; method)</span><br/><span class="error">E   +----------------------+----------------------+----------------------+</span><br/><span class="error">E   Traceback (most recent call last):</span><br/><span class="error">E     File &quot;/Users/evgen/PycharmProjects/Selenium/utilitize/utils.py&quot;, line 8, in assert_item_in_list</span><br/><span class="error">E       self.soft_assert(self.assertEqual, stop.text, value)</span><br/><span class="error">E     File &quot;/Users/evgen/PycharmProjects/Selenium/testcases/test_case1.py&quot;, line 32, in test_search_trip</span><br/><span class="error">E       self.ut.assert_item_in_list(search_result.get_all_element_one_stop(), &quot;1 Stop&quot;)</span><br/><span class="error">E     File &quot;/Users/evgen/PycharmProjects/Selenium/venv/lib/python3.11/site-packages/ddt.py&quot;, line 220, in wrapper</span><br/><span class="error">E       return func(self, *args, **kwargs)</span><br/><span class="error">E     File &quot;/Users/evgen/PycharmProjects/Selenium/venv/lib/python3.11/site-packages/softest/case.py&quot;, line 62, in soft_assert</span><br/><span class="error">E       assert_method(*arguments, **keywords)</span><br/><span class="error">E     File &quot;/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py&quot;, line 873, in assertEqual</span><br/><span class="error">E       assertion_func(first, second, msg=msg)</span><br/><span class="error">E     File &quot;/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py&quot;, line 1253, in assertMultiLineEqual</span><br/><span class="error">E       self.fail(self._formatMessage(msg, standardMsg))</span><br/><span class="error">E     File &quot;/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py&quot;, line 703, in fail</span><br/><span class="error">E       raise self.failureException(msg)</span><br/><span class="error">E   AssertionError: &#x27;&#x27; != &#x27;1 Stop&#x27;</span><br/><span class="error">E   + 1 Stop</span><br/><span class="error">E   </span><br/><span class="error">E   -+ [1/35] +-</span><br/><span class="error">E   </span><br/><span class="error">E   +----------------------+----------------------+----------------------+</span><br/><span class="error">E    Failure 2 (&quot;wrapper&quot; method)</span><br/><span class="error">E   +----------------------+----------------------+----------------------+</span><br/><span class="error">E   Traceback (most recent call last):</span><br/><span class="error">E     File &quot;/Users/evgen/PycharmProjects/Selenium/utilitize/utils.py&quot;, line 8, in assert_item_in_list</span><br/><span class="error">E       self.soft_assert(self.assertEqual, stop.text, value)</span><br/><span class="error">E     File &quot;/Users/evgen/PycharmProjects/Selenium/testcases/test_case1.py&quot;, line 32, in test_search_trip</span><br/><span class="error">E       self.ut.assert_item_in_list(search_result.get_all_element_one_stop(), &quot;1 Stop&quot;)</span><br/><span class="error">E     File &quot;/Users/evgen/PycharmProjects/Selenium/venv/lib/python3.11/site-packages/ddt.py&quot;, line 220, in wrapper</span><br/><span class="error">E       return func(self, *args, **kwargs)</span><br/><span class="error">E     File &quot;/Users/evgen/PycharmProjects/Selenium/venv/lib/python3.11/site-packages/softest/case.py&quot;, line 62, in soft_assert</span><br/><span class="error">E       assert_method(*arguments, **keywords)</span><br/><span class="error">E     File &quot;/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py&quot;, line 873, in assertEqual</span><br/><span class="error">E       assertion_func(first, second, msg=msg)</span><br/><span class="error">E     File &quot;/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py&quot;, line 1253, in assertMultiLineEqual</span><br/><span class="error">E       self.fail(self._formatMessage(msg, standardMsg))</span><br/><span class="error">E     File &quot;/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py&quot;, line 703, in fail</span><br/><span class="error">E       raise self.failureException(msg)</span><br/><span class="error">E   AssertionError: &#x27;&#x27; != &#x27;1 Stop&#x27;</span><br/><span class="error">E   + 1 Stop</span><br/><span class="error">E   </span><br/><span class="error">E   -+ [2/35] +-</span><br/><span class="error">E   </span><br/><span class="error">E   +----------------------+----------------------+----------------------+</span><br/><span class="error">E    Failure 3 (&quot;wrapper&quot; method)</span><br/><span class="error">E   +----------------------+----------------------+----------------------+</span><br/><span class="error">E   Traceback (most recent call last):</span><br/><span class="error">E     File &quot;/Users/evgen/PycharmProjects/Selenium/utilitize/utils.py&quot;, line 8, in assert_item_in_list</span><br/><span class="error">E       self.soft_assert(self.assertEqual, stop.text, value)</span><br/><span class="error">E     File &quot;/Users/evgen/PycharmProjects/Selenium/testcases/test_case1.py&quot;, line 32, in test_search_trip</span><br/><span class="error">E       self.ut.assert_item_in_list(search_result.get_all_element_one_stop(), &quot;1 Stop&quot;)</span><br/><span class="error">E     File &quot;/Users/evgen/PycharmProjects/Selenium/venv/lib/python3.11/site-packages/ddt.py&quot;, line 220, in wrapper</span><br/><span class="error">E       return func(self, *args, **kwargs)</span><br/><span class="error">E     File &quot;/Users/evgen/PycharmProjects/Selenium/venv/lib/python3.11/site-packages/softest/case.py&quot;, line 62, in soft_assert</span><br/><span class="error">E       assert_method(*arguments, **keywords)</span><br/><span class="error">E     File &quot;/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py&quot;, line 873, in assertEqual</span><br/><span class="error">E       assertion_func(first, second, msg=msg)</span><br/><span class="error">E     File &quot;/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py&quot;, line 1253, in assertMultiLineEqual</span><br/><span class="error">E       self.fail(self._formatMessage(msg, standardMsg))</span><br/><span class="error">E     File &quot;/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py&quot;, line 703, in fail</span><br/><span class="error">E       raise self.failureException(msg)</span><br/><span class="error">E   AssertionError: &#x27;&#x27; != &#x27;1 Stop&#x27;</span><br/><span class="error">E   + 1 Stop</span><br/><span class="error">E   </span><br/><span class="error">E   -+ [3/35] +-</span><br/><span class="error">E   </span><br/><span class="error">E   +----------------------+----------------------+----------------------+</span><br/><span class="error">E    Failure 4 (&quot;wrapper&quot; method)</span><br/><span class="error">E   +----------------------+----------------------+----------------------+</span><br/><span class="error">E   Traceback (most recent call last):</span><br/><span class="error">E     File &quot;/Users/evgen/PycharmProjects/Selenium/utilitize/utils.py&quot;, line 8, in assert_item_in_list</span><br/><span class="error">E       self.soft_assert(self.assertEqual, stop.text, value)</span><br/><span class="error">E     File &quot;/Users/evgen/PycharmProjects/Selenium/testcases/test_case1.py&quot;, line 32, in test_search_trip</span><br/><span class="error">E       self.ut.assert_item_in_list(search_result.get_all_element_one_stop(), &quot;1 Stop&quot;)</span><br/><span class="error">E     File &quot;/Users/evgen/PycharmProjects/Selenium/venv/lib/python3.11/site-packages/ddt.py&quot;, line 220, in wrapper</span><br/><span class="error">E       return func(self, *args, **kwargs)</span><br/><span class="error">E     File &quot;/Users/evgen/PycharmProjects/Selenium/venv/lib/python3.11/site-packages/softest/case.py&quot;, line 62, in soft_assert</span><br/><span class="error">E       assert_method(*arguments, **keywords)</span><br/><span class="error">E     File &quot;/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py&quot;, line 873, in assertEqual</span><br/><span class="error">E       assertion_func(first, second, msg=msg)</span><br/><span class="error">E     File &quot;/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py&quot;, line 1253, in assertMultiLineEqual</span><br/><span class="error">E       self.fail(self._formatMessage(msg, standardMsg))</span><br/><span class="error">E     File &quot;/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py&quot;, line 703, in fail</span><br/><span class="error">E       raise self.failureException(msg)</span><br/><span class="error">E   AssertionError: &#x27;&#x27; != &#x27;1 Stop&#x27;</span><br/><span class="error">E   + 1 Stop</span><br/><span class="error">E   </span><br/><span class="error">E   -+ [4/35] +-</span><br/><span class="error">E   </span><br/><span class="error">E   +----------------------+----------------------+----------------------+</span><br/><span class="error">E    Failure 5 (&quot;wrapper&quot; method)</span><br/><span class="error">E   +----------------------+----------------------+----------------------+</span><br/><span class="error">E   Traceback (most recent call last):</span><br/><span class="error">E     File &quot;/Users/evgen/PycharmProjects/Selenium/utilitize/utils.py&quot;, line 8, in assert_item_in_list</span><br/><span class="error">E       self.soft_assert(self.assertEqual, stop.text, value)</span><br/><span class="error">E     File &quot;/Users/evgen/PycharmProjects/Selenium/testcases/test_case1.py&quot;, line 32, in test_search_trip</span><br/><span class="error">E       self.ut.assert_item_in_list(search_result.get_all_element_one_stop(), &quot;1 Stop&quot;)</span><br/><span class="error">E     File &quot;/Users/evgen/PycharmProjects/Selenium/venv/lib/python3.11/site-packages/ddt.py&quot;, line 220, in wrapper</span><br/><span class="error">E       return func(self, *args, **kwargs)</span><br/><span class="error">E     File &quot;/Users/evgen/PycharmProjects/Selenium/venv/lib/python3.11/site-packages/softest/case.py&quot;, line 62, in soft_assert</span><br/><span class="error">E       assert_method(*arguments, **keywords)</span><br/><span class="error">E     File &quot;/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py&quot;, line 873, in assertEqual</span><br/><span class="error">E       assertion_func(first, second, msg=msg)</span><br/><span class="error">E     File &quot;/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py&quot;, line 1253, in assertMultiLineEqual</span><br/><span class="error">E       self.fail(self._formatMessage(msg, standardMsg))</span><br/><span class="error">E     File &quot;/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py&quot;, line 703, in fail</span><br/><span class="error">E       raise self.failureException(msg)</span><br/><span class="error">E   AssertionError: &#x27;&#x27; != &#x27;1 Stop&#x27;</span><br/><span class="error">E   + 1 Stop</span><br/><span class="error">E   </span><br/><span class="error">E   -+ [5/35] +-</span><br/><span class="error">E   </span><br/><span class="error">E   +----------------------+----------------------+----------------------+</span><br/><span class="error">E    Failure 6 (&quot;wrapper&quot; method)</span><br/><span class="error">E   +----------------------+----------------------+----------------------+</span><br/><span class="error">E   Traceback (most recent call last):</span><br/><span class="error">E     File &quot;/Users/evgen/PycharmProjects/Selenium/utilitize/utils.py&quot;, line 8, in assert_item_in_list</span><br/><span class="error">E       self.soft_assert(self.assertEqual, stop.text, value)</span><br/><span class="error">E     File &quot;/Users/evgen/PycharmProjects/Selenium/testcases/test_case1.py&quot;, line 32, in test_search_trip</span><br/><span class="error">E       self.ut.assert_item_in_list(search_result.get_all_element_one_stop(), &quot;1 Stop&quot;)</span><br/><span class="error">E     File &quot;/Users/evgen/PycharmProjects/Selenium/venv/lib/python3.11/site-packages/ddt.py&quot;, line 220, in wrapper</span><br/><span class="error">E       return func(self, *args, **kwargs)</span><br/><span class="error">E     File &quot;/Users/evgen/PycharmProjects/Selenium/venv/lib/python3.11/site-packages/softest/case.py&quot;, line 62, in soft_assert</span><br/><span class="error">E       assert_method(*arguments, **keywords)</span><br/><span class="error">E     File &quot;/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py&quot;, line 873, in assertEqual</span><br/><span class="error">E       assertion_func(first, second, msg=msg)</span><br/><span class="error">E     File &quot;/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py&quot;, line 1253, in assertMultiLineEqual</span><br/><span class="error">E       self.fail(self._formatMessage(msg, standardMsg))</span><br/><span class="error">E     File &quot;/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py&quot;, line 703, in fail</span><br/><span class="error">E       raise self.failureException(msg)</span><br/><span class="error">E   AssertionError: &#x27;&#x27; != &#x27;1 Stop&#x27;</span><br/><span class="error">E   + 1 Stop</span><br/><span class="error">E   </span><br/><span class="error">E   -+ [6/35] +-</span><br/><span class="error">E   </span><br/><span class="error">E   +----------------------+----------------------+----------------------+</span><br/><span class="error">E    Failure 7 (&quot;wrapper&quot; method)</span><br/><span class="error">E   +----------------------+----------------------+----------------------+</span><br/><span class="error">E   Traceback (most recent call last):</span><br/><span class="error">E     File &quot;/Users/evgen/PycharmProjects/Selenium/utilitize/utils.py&quot;, line 8, in assert_item_in_list</span><br/><span class="error">E       self.soft_assert(self.assertEqual, stop.text, value)</span><br/><span class="error">E     File &quot;/Users/evgen/PycharmProjects/Selenium/testcases/test_case1.py&quot;, line 32, in test_search_trip</span><br/><span class="error">E       self.ut.assert_item_in_list(search_result.get_all_element_one_stop(), &quot;1 Stop&quot;)</span><br/><span class="error">E     File &quot;/Users/evgen/PycharmProjects/Selenium/venv/lib/python3.11/site-packages/ddt.py&quot;, line 220, in wrapper</span><br/><span class="error">E       return func(self, *args, **kwargs)</span><br/><span class="error">E     File &quot;/Users/evgen/PycharmProjects/Selenium/venv/lib/python3.11/site-packages/softest/case.py&quot;, line 62, in soft_assert</span><br/><span class="error">E       assert_method(*arguments, **keywords)</span><br/><span class="error">E     File &quot;/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py&quot;, line 873, in assertEqual</span><br/><span class="error">E       assertion_func(first, second, msg=msg)</span><br/><span class="error">E     File &quot;/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py&quot;, line 1253, in assertMultiLineEqual</span><br/><span class="error">E       self.fail(self._formatMessage(msg, standardMsg))</span><br/><span class="error">E     File &quot;/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py&quot;, line 703, in fail</span><br/><span class="error">E       raise self.failureException(msg)</span><br/><span class="error">E   AssertionError: &#x27;&#x27; != &#x27;1 Stop&#x27;</span><br/><span class="error">E   + 1 Stop</span><br/><span class="error">E   </span><br/><span class="error">E   -+ [7/35] +-</span><br/><span class="error">E   </span><br/><span class="error">E   +----------------------+----------------------+----------------------+</span><br/><span class="error">E    Failure 8 (&quot;wrapper&quot; method)</span><br/><span class="error">E   +----------------------+----------------------+----------------------+</span><br/><span class="error">E   Traceback (most recent call last):</span><br/><span class="error">E     File &quot;/Users/evgen/PycharmProjects/Selenium/utilitize/utils.py&quot;, line 8, in assert_item_in_list</span><br/><span class="error">E       self.soft_assert(self.assertEqual, stop.text, value)</span><br/><span class="error">E     File &quot;/Users/evgen/PycharmProjects/Selenium/testcases/test_case1.py&quot;, line 32, in test_search_trip</span><br/><span class="error">E       self.ut.assert_item_in_list(search_result.get_all_element_one_stop(), &quot;1 Stop&quot;)</span><br/><span class="error">E     File &quot;/Users/evgen/PycharmProjects/Selenium/venv/lib/python3.11/site-packages/ddt.py&quot;, line 220, in wrapper</span><br/><span class="error">E       return func(self, *args, **kwargs)</span><br/><span class="error">E     File &quot;/Users/evgen/PycharmProjects/Selenium/venv/lib/python3.11/site-packages/softest/case.py&quot;, line 62, in soft_assert</span><br/><span class="error">E       assert_method(*arguments, **keywords)</span><br/><span class="error">E     File &quot;/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py&quot;, line 873, in assertEqual</span><br/><span class="error">E       assertion_func(first, second, msg=msg)</span><br/><span class="error">E     File &quot;/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py&quot;, line 1253, in assertMultiLineEqual</span><br/><span class="error">E       self.fail(self._formatMessage(msg, standardMsg))</span><br/><span class="error">E     File &quot;/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py&quot;, line 703, in fail</span><br/><span class="error">E       raise self.failureException(msg)</span><br/><span class="error">E   AssertionError: &#x27;&#x27; != &#x27;1 Stop&#x27;</span><br/><span class="error">E   + 1 Stop</span><br/><span class="error">E   </span><br/><span class="error">E   -+ [8/35] +-</span><br/><span class="error">E   </span><br/><span class="error">E   +----------------------+----------------------+----------------------+</span><br/><span class="error">E    Failure 9 (&quot;wrapper&quot; method)</span><br/><span class="error">E   +----------------------+----------------------+----------------------+</span><br/><span class="error">E   Traceback (most recent call last):</span><br/><span class="error">E     File &quot;/Users/evgen/PycharmProjects/Selenium/utilitize/utils.py&quot;, line 8, in assert_item_in_list</span><br/><span class="error">E       self.soft_assert(self.assertEqual, stop.text, value)</span><br/><span class="error">E     File &quot;/Users/evgen/PycharmProjects/Selenium/testcases/test_case1.py&quot;, line 32, in test_search_trip</span><br/><span class="error">E       self.ut.assert_item_in_list(search_result.get_all_element_one_stop(), &quot;1 Stop&quot;)</span><br/><span class="error">E     File &quot;/Users/evgen/PycharmProjects/Selenium/venv/lib/python3.11/site-packages/ddt.py&quot;, line 220, in wrapper</span><br/><span class="error">E       return func(self, *args, **kwargs)</span><br/><span class="error">E     File &quot;/Users/evgen/PycharmProjects/Selenium/venv/lib/python3.11/site-packages/softest/case.py&quot;, line 62, in soft_assert</span><br/><span class="error">E       assert_method(*arguments, **keywords)</span><br/><span class="error">E     File &quot;/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py&quot;, line 873, in assertEqual</span><br/><span class="error">E       assertion_func(first, second, msg=msg)</span><br/><span class="error">E     File &quot;/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py&quot;, line 1253, in assertMultiLineEqual</span><br/><span class="error">E       self.fail(self._formatMessage(msg, standardMsg))</span><br/><span class="error">E     File &quot;/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py&quot;, line 703, in fail</span><br/><span class="error">E       raise self.failureException(msg)</span><br/><span class="error">E   AssertionError: &#x27;&#x27; != &#x27;1 Stop&#x27;</span><br/><span class="error">E   + 1 Stop</span><br/><span class="error">E   </span><br/><span class="error">E   -+ [9/35] +-</span><br/><span class="error">E   </span><br/><span class="error">E   +----------------------+----------------------+----------------------+</span><br/><span class="error">E    Failure 10 (&quot;wrapper&quot; method)</span><br/><span class="error">E   +----------------------+----------------------+----------------------+</span><br/><span class="error">E   Traceback (most recent call last):</span><br/><span class="error">E     File &quot;/Users/evgen/PycharmProjects/Selenium/utilitize/utils.py&quot;, line 8, in assert_item_in_list</span><br/><span class="error">E       self.soft_assert(self.assertEqual, stop.text, value)</span><br/><span class="error">E     File &quot;/Users/evgen/PycharmProjects/Selenium/testcases/test_case1.py&quot;, line 32, in test_search_trip</span><br/><span class="error">E       self.ut.assert_item_in_list(search_result.get_all_element_one_stop(), &quot;1 Stop&quot;)</span><br/><span class="error">E     File &quot;/Users/evgen/PycharmProjects/Selenium/venv/lib/python3.11/site-packages/ddt.py&quot;, line 220, in wrapper</span><br/><span class="error">E       return func(self, *args, **kwargs)</span><br/><span class="error">E     File &quot;/Users/evgen/PycharmProjects/Selenium/venv/lib/python3.11/site-packages/softest/case.py&quot;, line 62, in soft_assert</span><br/><span class="error">E       assert_method(*arguments, **keywords)</span><br/><span class="error">E     File &quot;/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py&quot;, line 873, in assertEqual</span><br/><span class="error">E       assertion_func(first, second, msg=msg)</span><br/><span class="error">E     File &quot;/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py&quot;, line 1253, in assertMultiLineEqual</span><br/><span class="error">E       self.fail(self._formatMessage(msg, standardMsg))</span><br/><span class="error">E     File &quot;/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py&quot;, line 703, in fail</span><br/><span class="error">E       raise self.failureException(msg)</span><br/><span class="error">E   AssertionError: &#x27;&#x27; != &#x27;1 Stop&#x27;</span><br/><span class="error">E   + 1 Stop</span><br/><span class="error">E   </span><br/><span class="error">E   -+ [10/35] +-</span><br/><span class="error">E   </span><br/><span class="error">E   +----------------------+----------------------+----------------------+</span><br/><span class="error">E    Failure 11 (&quot;wrapper&quot; method)</span><br/><span class="error">E   +----------------------+----------------------+----------------------+</span><br/><span class="error">E   Traceback (most recent call last):</span><br/><span class="error">E     File &quot;/Users/evgen/PycharmProjects/Selenium/utilitize/utils.py&quot;, line 8, in assert_item_in_list</span><br/><span class="error">E       self.soft_assert(self.assertEqual, stop.text, value)</span><br/><span class="error">E     File &quot;/Users/evgen/PycharmProjects/Selenium/testcases/test_case1.py&quot;, line 32, in test_search_trip</span><br/><span class="error">E       self.ut.assert_item_in_list(search_result.get_all_element_one_stop(), &quot;1 Stop&quot;)</span><br/><span class="error">E     File &quot;/Users/evgen/PycharmProjects/Selenium/venv/lib/python3.11/site-packages/ddt.py&quot;, line 220, in wrapper</span><br/><span class="error">E       return func(self, *args, **kwargs)</span><br/><span class="error">E     File &quot;/Users/evgen/PycharmProjects/Selenium/venv/lib/python3.11/site-packages/softest/case.py&quot;, line 62, in soft_assert</span><br/><span class="error">E       assert_method(*arguments, **keywords)</span><br/><span class="error">E     File &quot;/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py&quot;, line 873, in assertEqual</span><br/><span class="error">E       assertion_func(first, second, msg=msg)</span><br/><span class="error">E     File &quot;/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py&quot;, line 1253, in assertMultiLineEqual</span><br/><span class="error">E       self.fail(self._formatMessage(msg, standardMsg))</span><br/><span class="error">E     File &quot;/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py&quot;, line 703, in fail</span><br/><span class="error">E       raise self.failureException(msg)</span><br/><span class="error">E   AssertionError: &#x27;&#x27; != &#x27;1 Stop&#x27;</span><br/><span class="error">E   + 1 Stop</span><br/><span class="error">E   </span><br/><span class="error">E   -+ [11/35] +-</span><br/><span class="error">E   </span><br/><span class="error">E   +----------------------+----------------------+----------------------+</span><br/><span class="error">E    Failure 12 (&quot;wrapper&quot; method)</span><br/><span class="error">E   +----------------------+----------------------+----------------------+</span><br/><span class="error">E   Traceback (most recent call last):</span><br/><span class="error">E     File &quot;/Users/evgen/PycharmProjects/Selenium/utilitize/utils.py&quot;, line 8, in assert_item_in_list</span><br/><span class="error">E       self.soft_assert(self.assertEqual, stop.text, value)</span><br/><span class="error">E     File &quot;/Users/evgen/PycharmProjects/Selenium/testcases/test_case1.py&quot;, line 32, in test_search_trip</span><br/><span class="error">E       self.ut.assert_item_in_list(search_result.get_all_element_one_stop(), &quot;1 Stop&quot;)</span><br/><span class="error">E     File &quot;/Users/evgen/PycharmProjects/Selenium/venv/lib/python3.11/site-packages/ddt.py&quot;, line 220, in wrapper</span><br/><span class="error">E       return func(self, *args, **kwargs)</span><br/><span class="error">E     File &quot;/Users/evgen/PycharmProjects/Selenium/venv/lib/python3.11/site-packages/softest/case.py&quot;, line 62, in soft_assert</span><br/><span class="error">E       assert_method(*arguments, **keywords)</span><br/><span class="error">E     File &quot;/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py&quot;, line 873, in assertEqual</span><br/><span class="error">E       assertion_func(first, second, msg=msg)</span><br/><span class="error">E     File &quot;/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py&quot;, line 1253, in assertMultiLineEqual</span><br/><span class="error">E       self.fail(self._formatMessage(msg, standardMsg))</span><br/><span class="error">E     File &quot;/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py&quot;, line 703, in fail</span><br/><span class="error">E       raise self.failureException(msg)</span><br/><span class="error">E   AssertionError: &#x27;&#x27; != &#x27;1 Stop&#x27;</span><br/><span class="error">E   + 1 Stop</span><br/><span class="error">E   </span><br/><span class="error">E   -+ [12/35] +-</span><br/><span class="error">E   </span><br/><span class="error">E   +----------------------+----------------------+----------------------+</span><br/><span class="error">E    Failure 13 (&quot;wrapper&quot; method)</span><br/><span class="error">E   +----------------------+----------------------+----------------------+</span><br/><span class="error">E   Traceback (most recent call last):</span><br/><span class="error">E     File &quot;/Users/evgen/PycharmProjects/Selenium/utilitize/utils.py&quot;, line 8, in assert_item_in_list</span><br/><span class="error">E       self.soft_assert(self.assertEqual, stop.text, value)</span><br/><span class="error">E     File &quot;/Users/evgen/PycharmProjects/Selenium/testcases/test_case1.py&quot;, line 32, in test_search_trip</span><br/><span class="error">E       self.ut.assert_item_in_list(search_result.get_all_element_one_stop(), &quot;1 Stop&quot;)</span><br/><span class="error">E     File &quot;/Users/evgen/PycharmProjects/Selenium/venv/lib/python3.11/site-packages/ddt.py&quot;, line 220, in wrapper</span><br/><span class="error">E       return func(self, *args, **kwargs)</span><br/><span class="error">E     File &quot;/Users/evgen/PycharmProjects/Selenium/venv/lib/python3.11/site-packages/softest/case.py&quot;, line 62, in soft_assert</span><br/><span class="error">E       assert_method(*arguments, **keywords)</span><br/><span class="error">E     File &quot;/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py&quot;, line 873, in assertEqual</span><br/><span class="error">E       assertion_func(first, second, msg=msg)</span><br/><span class="error">E     File &quot;/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py&quot;, line 1253, in assertMultiLineEqual</span><br/><span class="error">E       self.fail(self._formatMessage(msg, standardMsg))</span><br/><span class="error">E     File &quot;/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py&quot;, line 703, in fail</span><br/><span class="error">E       raise self.failureException(msg)</span><br/><span class="error">E   AssertionError: &#x27;&#x27; != &#x27;1 Stop&#x27;</span><br/><span class="error">E   + 1 Stop</span><br/><span class="error">E   </span><br/><span class="error">E   -+ [13/35] +-</span><br/><span class="error">E   </span><br/><span class="error">E   +----------------------+----------------------+----------------------+</span><br/><span class="error">E    Failure 14 (&quot;wrapper&quot; method)</span><br/><span class="error">E   +----------------------+----------------------+----------------------+</span><br/><span class="error">E   Traceback (most recent call last):</span><br/><span class="error">E     File &quot;/Users/evgen/PycharmProjects/Selenium/utilitize/utils.py&quot;, line 8, in assert_item_in_list</span><br/><span class="error">E       self.soft_assert(self.assertEqual, stop.text, value)</span><br/><span class="error">E     File &quot;/Users/evgen/PycharmProjects/Selenium/testcases/test_case1.py&quot;, line 32, in test_search_trip</span><br/><span class="error">E       self.ut.assert_item_in_list(search_result.get_all_element_one_stop(), &quot;1 Stop&quot;)</span><br/><span class="error">E     File &quot;/Users/evgen/PycharmProjects/Selenium/venv/lib/python3.11/site-packages/ddt.py&quot;, line 220, in wrapper</span><br/><span class="error">E       return func(self, *args, **kwargs)</span><br/><span class="error">E     File &quot;/Users/evgen/PycharmProjects/Selenium/venv/lib/python3.11/site-packages/softest/case.py&quot;, line 62, in soft_assert</span><br/><span class="error">E       assert_method(*arguments, **keywords)</span><br/><span class="error">E     File &quot;/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py&quot;, line 873, in assertEqual</span><br/><span class="error">E       assertion_func(first, second, msg=msg)</span><br/><span class="error">E     File &quot;/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py&quot;, line 1253, in assertMultiLineEqual</span><br/><span class="error">E       self.fail(self._formatMessage(msg, standardMsg))</span><br/><span class="error">E     File &quot;/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py&quot;, line 703, in fail</span><br/><span class="error">E       raise self.failureException(msg)</span><br/><span class="error">E   AssertionError: &#x27;&#x27; != &#x27;1 Stop&#x27;</span><br/><span class="error">E   + 1 Stop</span><br/><span class="error">E   </span><br/><span class="error">E   -+ [14/35] +-</span><br/><span class="error">E   </span><br/><span class="error">E   +----------------------+----------------------+----------------------+</span><br/><span class="error">E    Failure 15 (&quot;wrapper&quot; method)</span><br/><span class="error">E   +----------------------+----------------------+----------------------+</span><br/><span class="error">E   Traceback (most recent call last):</span><br/><span class="error">E     File &quot;/Users/evgen/PycharmProjects/Selenium/utilitize/utils.py&quot;, line 8, in assert_item_in_list</span><br/><span class="error">E       self.soft_assert(self.assertEqual, stop.text, value)</span><br/><span class="error">E     File &quot;/Users/evgen/PycharmProjects/Selenium/testcases/test_case1.py&quot;, line 32, in test_search_trip</span><br/><span class="error">E       self.ut.assert_item_in_list(search_result.get_all_element_one_stop(), &quot;1 Stop&quot;)</span><br/><span class="error">E     File &quot;/Users/evgen/PycharmProjects/Selenium/venv/lib/python3.11/site-packages/ddt.py&quot;, line 220, in wrapper</span><br/><span class="error">E       return func(self, *args, **kwargs)</span><br/><span class="error">E     File &quot;/Users/evgen/PycharmProjects/Selenium/venv/lib/python3.11/site-packages/softest/case.py&quot;, line 62, in soft_assert</span><br/><span class="error">E       assert_method(*arguments, **keywords)</span><br/><span class="error">E     File &quot;/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py&quot;, line 873, in assertEqual</span><br/><span class="error">E       assertion_func(first, second, msg=msg)</span><br/><span class="error">E     File &quot;/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py&quot;, line 1253, in assertMultiLineEqual</span><br/><span class="error">E       self.fail(self._formatMessage(msg, standardMsg))</span><br/><span class="error">E     File &quot;/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py&quot;, line 703, in fail</span><br/><span class="error">E       raise self.failureException(msg)</span><br/><span class="error">E   AssertionError: &#x27;&#x27; != &#x27;1 Stop&#x27;</span><br/><span class="error">E   + 1 Stop</span><br/><span class="error">E   </span><br/><span class="error">E   -+ [15/35] +-</span><br/><span class="error">E   </span><br/><span class="error">E   +----------------------+----------------------+----------------------+</span><br/><span class="error">E    Failure 16 (&quot;wrapper&quot; method)</span><br/><span class="error">E   +----------------------+----------------------+----------------------+</span><br/><span class="error">E   Traceback (most recent call last):</span><br/><span class="error">E     File &quot;/Users/evgen/PycharmProjects/Selenium/utilitize/utils.py&quot;, line 8, in assert_item_in_list</span><br/><span class="error">E       self.soft_assert(self.assertEqual, stop.text, value)</span><br/><span class="error">E     File &quot;/Users/evgen/PycharmProjects/Selenium/testcases/test_case1.py&quot;, line 32, in test_search_trip</span><br/><span class="error">E       self.ut.assert_item_in_list(search_result.get_all_element_one_stop(), &quot;1 Stop&quot;)</span><br/><span class="error">E     File &quot;/Users/evgen/PycharmProjects/Selenium/venv/lib/python3.11/site-packages/ddt.py&quot;, line 220, in wrapper</span><br/><span class="error">E       return func(self, *args, **kwargs)</span><br/><span class="error">E     File &quot;/Users/evgen/PycharmProjects/Selenium/venv/lib/python3.11/site-packages/softest/case.py&quot;, line 62, in soft_assert</span><br/><span class="error">E       assert_method(*arguments, **keywords)</span><br/><span class="error">E     File &quot;/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py&quot;, line 873, in assertEqual</span><br/><span class="error">E       assertion_func(first, second, msg=msg)</span><br/><span class="error">E     File &quot;/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py&quot;, line 1253, in assertMultiLineEqual</span><br/><span class="error">E       self.fail(self._formatMessage(msg, standardMsg))</span><br/><span class="error">E     File &quot;/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py&quot;, line 703, in fail</span><br/><span class="error">E       raise self.failureException(msg)</span><br/><span class="error">E   AssertionError: &#x27;&#x27; != &#x27;1 Stop&#x27;</span><br/><span class="error">E   + 1 Stop</span><br/><span class="error">E   </span><br/><span class="error">E   -+ [16/35] +-</span><br/><span class="error">E   </span><br/><span class="error">E   +----------------------+----------------------+----------------------+</span><br/><span class="error">E    Failure 17 (&quot;wrapper&quot; method)</span><br/><span class="error">E   +----------------------+----------------------+----------------------+</span><br/><span class="error">E   Traceback (most recent call last):</span><br/><span class="error">E     File &quot;/Users/evgen/PycharmProjects/Selenium/utilitize/utils.py&quot;, line 8, in assert_item_in_list</span><br/><span class="error">E       self.soft_assert(self.assertEqual, stop.text, value)</span><br/><span class="error">E     File &quot;/Users/evgen/PycharmProjects/Selenium/testcases/test_case1.py&quot;, line 32, in test_search_trip</span><br/><span class="error">E       self.ut.assert_item_in_list(search_result.get_all_element_one_stop(), &quot;1 Stop&quot;)</span><br/><span class="error">E     File &quot;/Users/evgen/PycharmProjects/Selenium/venv/lib/python3.11/site-packages/ddt.py&quot;, line 220, in wrapper</span><br/><span class="error">E       return func(self, *args, **kwargs)</span><br/><span class="error">E     File &quot;/Users/evgen/PycharmProjects/Selenium/venv/lib/python3.11/site-packages/softest/case.py&quot;, line 62, in soft_assert</span><br/><span class="error">E       assert_method(*arguments, **keywords)</span><br/><span class="error">E     File &quot;/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py&quot;, line 873, in assertEqual</span><br/><span class="error">E       assertion_func(first, second, msg=msg)</span><br/><span class="error">E     File &quot;/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py&quot;, line 1253, in assertMultiLineEqual</span><br/><span class="error">E       self.fail(self._formatMessage(msg, standardMsg))</span><br/><span class="error">E     File &quot;/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py&quot;, line 703, in fail</span><br/><span class="error">E       raise self.failureException(msg)</span><br/><span class="error">E   AssertionError: &#x27;&#x27; != &#x27;1 Stop&#x27;</span><br/><span class="error">E   + 1 Stop</span><br/><span class="error">E   </span><br/><span class="error">E   -+ [17/35] +-</span><br/><span class="error">E   </span><br/><span class="error">E   +----------------------+----------------------+----------------------+</span><br/><span class="error">E    Failure 18 (&quot;wrapper&quot; method)</span><br/><span class="error">E   +----------------------+----------------------+----------------------+</span><br/><span class="error">E   Traceback (most recent call last):</span><br/><span class="error">E     File &quot;/Users/evgen/PycharmProjects/Selenium/utilitize/utils.py&quot;, line 8, in assert_item_in_list</span><br/><span class="error">E       self.soft_assert(self.assertEqual, stop.text, value)</span><br/><span class="error">E     File &quot;/Users/evgen/PycharmProjects/Selenium/testcases/test_case1.py&quot;, line 32, in test_search_trip</span><br/><span class="error">E       self.ut.assert_item_in_list(search_result.get_all_element_one_stop(), &quot;1 Stop&quot;)</span><br/><span class="error">E     File &quot;/Users/evgen/PycharmProjects/Selenium/venv/lib/python3.11/site-packages/ddt.py&quot;, line 220, in wrapper</span><br/><span class="error">E       return func(self, *args, **kwargs)</span><br/><span class="error">E     File &quot;/Users/evgen/PycharmProjects/Selenium/venv/lib/python3.11/site-packages/softest/case.py&quot;, line 62, in soft_assert</span><br/><span class="error">E       assert_method(*arguments, **keywords)</span><br/><span class="error">E     File &quot;/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py&quot;, line 873, in assertEqual</span><br/><span class="error">E       assertion_func(first, second, msg=msg)</span><br/><span class="error">E     File &quot;/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py&quot;, line 1253, in assertMultiLineEqual</span><br/><span class="error">E       self.fail(self._formatMessage(msg, standardMsg))</span><br/><span class="error">E     File &quot;/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py&quot;, line 703, in fail</span><br/><span class="error">E       raise self.failureException(msg)</span><br/><span class="error">E   AssertionError: &#x27;&#x27; != &#x27;1 Stop&#x27;</span><br/><span class="error">E   + 1 Stop</span><br/><span class="error">E   </span><br/><span class="error">E   -+ [18/35] +-</span><br/><span class="error">E   </span><br/><span class="error">E   +----------------------+----------------------+----------------------+</span><br/><span class="error">E    Failure 19 (&quot;wrapper&quot; method)</span><br/><span class="error">E   +----------------------+----------------------+----------------------+</span><br/><span class="error">E   Traceback (most recent call last):</span><br/><span class="error">E     File &quot;/Users/evgen/PycharmProjects/Selenium/utilitize/utils.py&quot;, line 8, in assert_item_in_list</span><br/><span class="error">E       self.soft_assert(self.assertEqual, stop.text, value)</span><br/><span class="error">E     File &quot;/Users/evgen/PycharmProjects/Selenium/testcases/test_case1.py&quot;, line 32, in test_search_trip</span><br/><span class="error">E       self.ut.assert_item_in_list(search_result.get_all_element_one_stop(), &quot;1 Stop&quot;)</span><br/><span class="error">E     File &quot;/Users/evgen/PycharmProjects/Selenium/venv/lib/python3.11/site-packages/ddt.py&quot;, line 220, in wrapper</span><br/><span class="error">E       return func(self, *args, **kwargs)</span><br/><span class="error">E     File &quot;/Users/evgen/PycharmProjects/Selenium/venv/lib/python3.11/site-packages/softest/case.py&quot;, line 62, in soft_assert</span><br/><span class="error">E       assert_method(*arguments, **keywords)</span><br/><span class="error">E     File &quot;/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py&quot;, line 873, in assertEqual</span><br/><span class="error">E       assertion_func(first, second, msg=msg)</span><br/><span class="error">E     File &quot;/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py&quot;, line 1253, in assertMultiLineEqual</span><br/><span class="error">E       self.fail(self._formatMessage(msg, standardMsg))</span><br/><span class="error">E     File &quot;/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py&quot;, line 703, in fail</span><br/><span class="error">E       raise self.failureException(msg)</span><br/><span class="error">E   AssertionError: &#x27;&#x27; != &#x27;1 Stop&#x27;</span><br/><span class="error">E   + 1 Stop</span><br/><span class="error">E   </span><br/><span class="error">E   -+ [19/35] +-</span><br/><span class="error">E   </span><br/><span class="error">E   +----------------------+----------------------+----------------------+</span><br/><span class="error">E    Failure 20 (&quot;wrapper&quot; method)</span><br/><span class="error">E   +----------------------+----------------------+----------------------+</span><br/><span class="error">E   Traceback (most recent call last):</span><br/><span class="error">E     File &quot;/Users/evgen/PycharmProjects/Selenium/utilitize/utils.py&quot;, line 8, in assert_item_in_list</span><br/><span class="error">E       self.soft_assert(self.assertEqual, stop.text, value)</span><br/><span class="error">E     File &quot;/Users/evgen/PycharmProjects/Selenium/testcases/test_case1.py&quot;, line 32, in test_search_trip</span><br/><span class="error">E       self.ut.assert_item_in_list(search_result.get_all_element_one_stop(), &quot;1 Stop&quot;)</span><br/><span class="error">E     File &quot;/Users/evgen/PycharmProjects/Selenium/venv/lib/python3.11/site-packages/ddt.py&quot;, line 220, in wrapper</span><br/><span class="error">E       return func(self, *args, **kwargs)</span><br/><span class="error">E     File &quot;/Users/evgen/PycharmProjects/Selenium/venv/lib/python3.11/site-packages/softest/case.py&quot;, line 62, in soft_assert</span><br/><span class="error">E       assert_method(*arguments, **keywords)</span><br/><span class="error">E     File &quot;/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py&quot;, line 873, in assertEqual</span><br/><span class="error">E       assertion_func(first, second, msg=msg)</span><br/><span class="error">E     File &quot;/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py&quot;, line 1253, in assertMultiLineEqual</span><br/><span class="error">E       self.fail(self._formatMessage(msg, standardMsg))</span><br/><span class="error">E     File &quot;/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py&quot;, line 703, in fail</span><br/><span class="error">E       raise self.failureException(msg)</span><br/><span class="error">E   AssertionError: &#x27;&#x27; != &#x27;1 Stop&#x27;</span><br/><span class="error">E   + 1 Stop</span><br/><span class="error">E   </span><br/><span class="error">E   -+ [20/35] +-</span><br/><span class="error">E   </span><br/><span class="error">E   +----------------------+----------------------+----------------------+</span><br/><span class="error">E    Failure 21 (&quot;wrapper&quot; method)</span><br/><span class="error">E   +----------------------+----------------------+----------------------+</span><br/><span class="error">E   Traceback (most recent call last):</span><br/><span class="error">E     File &quot;/Users/evgen/PycharmProjects/Selenium/utilitize/utils.py&quot;, line 8, in assert_item_in_list</span><br/><span class="error">E       self.soft_assert(self.assertEqual, stop.text, value)</span><br/><span class="error">E     File &quot;/Users/evgen/PycharmProjects/Selenium/testcases/test_case1.py&quot;, line 32, in test_search_trip</span><br/><span class="error">E       self.ut.assert_item_in_list(search_result.get_all_element_one_stop(), &quot;1 Stop&quot;)</span><br/><span class="error">E     File &quot;/Users/evgen/PycharmProjects/Selenium/venv/lib/python3.11/site-packages/ddt.py&quot;, line 220, in wrapper</span><br/><span class="error">E       return func(self, *args, **kwargs)</span><br/><span class="error">E     File &quot;/Users/evgen/PycharmProjects/Selenium/venv/lib/python3.11/site-packages/softest/case.py&quot;, line 62, in soft_assert</span><br/><span class="error">E       assert_method(*arguments, **keywords)</span><br/><span class="error">E     File &quot;/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py&quot;, line 873, in assertEqual</span><br/><span class="error">E       assertion_func(first, second, msg=msg)</span><br/><span class="error">E     File &quot;/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py&quot;, line 1253, in assertMultiLineEqual</span><br/><span class="error">E       self.fail(self._formatMessage(msg, standardMsg))</span><br/><span class="error">E     File &quot;/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py&quot;, line 703, in fail</span><br/><span class="error">E       raise self.failureException(msg)</span><br/><span class="error">E   AssertionError: &#x27;&#x27; != &#x27;1 Stop&#x27;</span><br/><span class="error">E   + 1 Stop</span><br/><span class="error">E   </span><br/><span class="error">E   -+ [21/35] +-</span><br/><span class="error">E   </span><br/><span class="error">E   +----------------------+----------------------+----------------------+</span><br/><span class="error">E    Failure 22 (&quot;wrapper&quot; method)</span><br/><span class="error">E   +----------------------+----------------------+----------------------+</span><br/><span class="error">E   Traceback (most recent call last):</span><br/><span class="error">E     File &quot;/Users/evgen/PycharmProjects/Selenium/utilitize/utils.py&quot;, line 8, in assert_item_in_list</span><br/><span class="error">E       self.soft_assert(self.assertEqual, stop.text, value)</span><br/><span class="error">E     File &quot;/Users/evgen/PycharmProjects/Selenium/testcases/test_case1.py&quot;, line 32, in test_search_trip</span><br/><span class="error">E       self.ut.assert_item_in_list(search_result.get_all_element_one_stop(), &quot;1 Stop&quot;)</span><br/><span class="error">E     File &quot;/Users/evgen/PycharmProjects/Selenium/venv/lib/python3.11/site-packages/ddt.py&quot;, line 220, in wrapper</span><br/><span class="error">E       return func(self, *args, **kwargs)</span><br/><span class="error">E     File &quot;/Users/evgen/PycharmProjects/Selenium/venv/lib/python3.11/site-packages/softest/case.py&quot;, line 62, in soft_assert</span><br/><span class="error">E       assert_method(*arguments, **keywords)</span><br/><span class="error">E     File &quot;/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py&quot;, line 873, in assertEqual</span><br/><span class="error">E       assertion_func(first, second, msg=msg)</span><br/><span class="error">E     File &quot;/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py&quot;, line 1253, in assertMultiLineEqual</span><br/><span class="error">E       self.fail(self._formatMessage(msg, standardMsg))</span><br/><span class="error">E     File &quot;/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py&quot;, line 703, in fail</span><br/><span class="error">E       raise self.failureException(msg)</span><br/><span class="error">E   AssertionError: &#x27;&#x27; != &#x27;1 Stop&#x27;</span><br/><span class="error">E   + 1 Stop</span><br/><span class="error">E   </span><br/><span class="error">E   -+ [22/35] +-</span><br/><span class="error">E   </span><br/><span class="error">E   +----------------------+----------------------+----------------------+</span><br/><span class="error">E    Failure 23 (&quot;wrapper&quot; method)</span><br/><span class="error">E   +----------------------+----------------------+----------------------+</span><br/><span class="error">E   Traceback (most recent call last):</span><br/><span class="error">E     File &quot;/Users/evgen/PycharmProjects/Selenium/utilitize/utils.py&quot;, line 8, in assert_item_in_list</span><br/><span class="error">E       self.soft_assert(self.assertEqual, stop.text, value)</span><br/><span class="error">E     File &quot;/Users/evgen/PycharmProjects/Selenium/testcases/test_case1.py&quot;, line 32, in test_search_trip</span><br/><span class="error">E       self.ut.assert_item_in_list(search_result.get_all_element_one_stop(), &quot;1 Stop&quot;)</span><br/><span class="error">E     File &quot;/Users/evgen/PycharmProjects/Selenium/venv/lib/python3.11/site-packages/ddt.py&quot;, line 220, in wrapper</span><br/><span class="error">E       return func(self, *args, **kwargs)</span><br/><span class="error">E     File &quot;/Users/evgen/PycharmProjects/Selenium/venv/lib/python3.11/site-packages/softest/case.py&quot;, line 62, in soft_assert</span><br/><span class="error">E       assert_method(*arguments, **keywords)</span><br/><span class="error">E     File &quot;/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py&quot;, line 873, in assertEqual</span><br/><span class="error">E       assertion_func(first, second, msg=msg)</span><br/><span class="error">E     File &quot;/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py&quot;, line 1253, in assertMultiLineEqual</span><br/><span class="error">E       self.fail(self._formatMessage(msg, standardMsg))</span><br/><span class="error">E     File &quot;/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py&quot;, line 703, in fail</span><br/><span class="error">E       raise self.failureException(msg)</span><br/><span class="error">E   AssertionError: &#x27;&#x27; != &#x27;1 Stop&#x27;</span><br/><span class="error">E   + 1 Stop</span><br/><span class="error">E   </span><br/><span class="error">E   -+ [23/35] +-</span><br/><span class="error">E   </span><br/><span class="error">E   +----------------------+----------------------+----------------------+</span><br/><span class="error">E    Failure 24 (&quot;wrapper&quot; method)</span><br/><span class="error">E   +----------------------+----------------------+----------------------+</span><br/><span class="error">E   Traceback (most recent call last):</span><br/><span class="error">E     File &quot;/Users/evgen/PycharmProjects/Selenium/utilitize/utils.py&quot;, line 8, in assert_item_in_list</span><br/><span class="error">E       self.soft_assert(self.assertEqual, stop.text, value)</span><br/><span class="error">E     File &quot;/Users/evgen/PycharmProjects/Selenium/testcases/test_case1.py&quot;, line 32, in test_search_trip</span><br/><span class="error">E       self.ut.assert_item_in_list(search_result.get_all_element_one_stop(), &quot;1 Stop&quot;)</span><br/><span class="error">E     File &quot;/Users/evgen/PycharmProjects/Selenium/venv/lib/python3.11/site-packages/ddt.py&quot;, line 220, in wrapper</span><br/><span class="error">E       return func(self, *args, **kwargs)</span><br/><span class="error">E     File &quot;/Users/evgen/PycharmProjects/Selenium/venv/lib/python3.11/site-packages/softest/case.py&quot;, line 62, in soft_assert</span><br/><span class="error">E       assert_method(*arguments, **keywords)</span><br/><span class="error">E     File &quot;/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py&quot;, line 873, in assertEqual</span><br/><span class="error">E       assertion_func(first, second, msg=msg)</span><br/><span class="error">E     File &quot;/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py&quot;, line 1253, in assertMultiLineEqual</span><br/><span class="error">E       self.fail(self._formatMessage(msg, standardMsg))</span><br/><span class="error">E     File &quot;/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py&quot;, line 703, in fail</span><br/><span class="error">E       raise self.failureException(msg)</span><br/><span class="error">E   AssertionError: &#x27;&#x27; != &#x27;1 Stop&#x27;</span><br/><span class="error">E   + 1 Stop</span><br/><span class="error">E   </span><br/><span class="error">E   -+ [24/35] +-</span><br/><span class="error">E   </span><br/><span class="error">E   +----------------------+----------------------+----------------------+</span><br/><span class="error">E    Failure 25 (&quot;wrapper&quot; method)</span><br/><span class="error">E   +----------------------+----------------------+----------------------+</span><br/><span class="error">E   Traceback (most recent call last):</span><br/><span class="error">E     File &quot;/Users/evgen/PycharmProjects/Selenium/utilitize/utils.py&quot;, line 8, in assert_item_in_list</span><br/><span class="error">E       self.soft_assert(self.assertEqual, stop.text, value)</span><br/><span class="error">E     File &quot;/Users/evgen/PycharmProjects/Selenium/testcases/test_case1.py&quot;, line 32, in test_search_trip</span><br/><span class="error">E       self.ut.assert_item_in_list(search_result.get_all_element_one_stop(), &quot;1 Stop&quot;)</span><br/><span class="error">E     File &quot;/Users/evgen/PycharmProjects/Selenium/venv/lib/python3.11/site-packages/ddt.py&quot;, line 220, in wrapper</span><br/><span class="error">E       return func(self, *args, **kwargs)</span><br/><span class="error">E     File &quot;/Users/evgen/PycharmProjects/Selenium/venv/lib/python3.11/site-packages/softest/case.py&quot;, line 62, in soft_assert</span><br/><span class="error">E       assert_method(*arguments, **keywords)</span><br/><span class="error">E     File &quot;/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py&quot;, line 873, in assertEqual</span><br/><span class="error">E       assertion_func(first, second, msg=msg)</span><br/><span class="error">E     File &quot;/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py&quot;, line 1253, in assertMultiLineEqual</span><br/><span class="error">E       self.fail(self._formatMessage(msg, standardMsg))</span><br/><span class="error">E     File &quot;/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py&quot;, line 703, in fail</span><br/><span class="error">E       raise self.failureException(msg)</span><br/><span class="error">E   AssertionError: &#x27;&#x27; != &#x27;1 Stop&#x27;</span><br/><span class="error">E   + 1 Stop</span><br/><span class="error">E   </span><br/><span class="error">E   -+ [25/35] +-</span><br/><span class="error">E   </span><br/><span class="error">E   +----------------------+----------------------+----------------------+</span><br/><span class="error">E    Failure 26 (&quot;wrapper&quot; method)</span><br/><span class="error">E   +----------------------+----------------------+----------------------+</span><br/><span class="error">E   Traceback (most recent call last):</span><br/><span class="error">E     File &quot;/Users/evgen/PycharmProjects/Selenium/utilitize/utils.py&quot;, line 8, in assert_item_in_list</span><br/><span class="error">E       self.soft_assert(self.assertEqual, stop.text, value)</span><br/><span class="error">E     File &quot;/Users/evgen/PycharmProjects/Selenium/testcases/test_case1.py&quot;, line 32, in test_search_trip</span><br/><span class="error">E       self.ut.assert_item_in_list(search_result.get_all_element_one_stop(), &quot;1 Stop&quot;)</span><br/><span class="error">E     File &quot;/Users/evgen/PycharmProjects/Selenium/venv/lib/python3.11/site-packages/ddt.py&quot;, line 220, in wrapper</span><br/><span class="error">E       return func(self, *args, **kwargs)</span><br/><span class="error">E     File &quot;/Users/evgen/PycharmProjects/Selenium/venv/lib/python3.11/site-packages/softest/case.py&quot;, line 62, in soft_assert</span><br/><span class="error">E       assert_method(*arguments, **keywords)</span><br/><span class="error">E     File &quot;/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py&quot;, line 873, in assertEqual</span><br/><span class="error">E       assertion_func(first, second, msg=msg)</span><br/><span class="error">E     File &quot;/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py&quot;, line 1253, in assertMultiLineEqual</span><br/><span class="error">E       self.fail(self._formatMessage(msg, standardMsg))</span><br/><span class="error">E     File &quot;/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py&quot;, line 703, in fail</span><br/><span class="error">E       raise self.failureException(msg)</span><br/><span class="error">E   AssertionError: &#x27;&#x27; != &#x27;1 Stop&#x27;</span><br/><span class="error">E   + 1 Stop</span><br/><span class="error">E   </span><br/><span class="error">E   -+ [26/35] +-</span><br/><span class="error">E   </span><br/><span class="error">E   +----------------------+----------------------+----------------------+</span><br/><span class="error">E    Failure 27 (&quot;wrapper&quot; method)</span><br/><span class="error">E   +----------------------+----------------------+----------------------+</span><br/><span class="error">E   Traceback (most recent call last):</span><br/><span class="error">E     File &quot;/Users/evgen/PycharmProjects/Selenium/utilitize/utils.py&quot;, line 8, in assert_item_in_list</span><br/><span class="error">E       self.soft_assert(self.assertEqual, stop.text, value)</span><br/><span class="error">E     File &quot;/Users/evgen/PycharmProjects/Selenium/testcases/test_case1.py&quot;, line 32, in test_search_trip</span><br/><span class="error">E       self.ut.assert_item_in_list(search_result.get_all_element_one_stop(), &quot;1 Stop&quot;)</span><br/><span class="error">E     File &quot;/Users/evgen/PycharmProjects/Selenium/venv/lib/python3.11/site-packages/ddt.py&quot;, line 220, in wrapper</span><br/><span class="error">E       return func(self, *args, **kwargs)</span><br/><span class="error">E     File &quot;/Users/evgen/PycharmProjects/Selenium/venv/lib/python3.11/site-packages/softest/case.py&quot;, line 62, in soft_assert</span><br/><span class="error">E       assert_method(*arguments, **keywords)</span><br/><span class="error">E     File &quot;/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py&quot;, line 873, in assertEqual</span><br/><span class="error">E       assertion_func(first, second, msg=msg)</span><br/><span class="error">E     File &quot;/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py&quot;, line 1253, in assertMultiLineEqual</span><br/><span class="error">E       self.fail(self._formatMessage(msg, standardMsg))</span><br/><span class="error">E     File &quot;/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py&quot;, line 703, in fail</span><br/><span class="error">E       raise self.failureException(msg)</span><br/><span class="error">E   AssertionError: &#x27;&#x27; != &#x27;1 Stop&#x27;</span><br/><span class="error">E   + 1 Stop</span><br/><span class="error">E   </span><br/><span class="error">E   -+ [27/35] +-</span><br/><span class="error">E   </span><br/><span class="error">E   +----------------------+----------------------+----------------------+</span><br/><span class="error">E    Failure 28 (&quot;wrapper&quot; method)</span><br/><span class="error">E   +----------------------+----------------------+----------------------+</span><br/><span class="error">E   Traceback (most recent call last):</span><br/><span class="error">E     File &quot;/Users/evgen/PycharmProjects/Selenium/utilitize/utils.py&quot;, line 8, in assert_item_in_list</span><br/><span class="error">E       self.soft_assert(self.assertEqual, stop.text, value)</span><br/><span class="error">E     File &quot;/Users/evgen/PycharmProjects/Selenium/testcases/test_case1.py&quot;, line 32, in test_search_trip</span><br/><span class="error">E       self.ut.assert_item_in_list(search_result.get_all_element_one_stop(), &quot;1 Stop&quot;)</span><br/><span class="error">E     File &quot;/Users/evgen/PycharmProjects/Selenium/venv/lib/python3.11/site-packages/ddt.py&quot;, line 220, in wrapper</span><br/><span class="error">E       return func(self, *args, **kwargs)</span><br/><span class="error">E     File &quot;/Users/evgen/PycharmProjects/Selenium/venv/lib/python3.11/site-packages/softest/case.py&quot;, line 62, in soft_assert</span><br/><span class="error">E       assert_method(*arguments, **keywords)</span><br/><span class="error">E     File &quot;/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py&quot;, line 873, in assertEqual</span><br/><span class="error">E       assertion_func(first, second, msg=msg)</span><br/><span class="error">E     File &quot;/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py&quot;, line 1253, in assertMultiLineEqual</span><br/><span class="error">E       self.fail(self._formatMessage(msg, standardMsg))</span><br/><span class="error">E     File &quot;/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py&quot;, line 703, in fail</span><br/><span class="error">E       raise self.failureException(msg)</span><br/><span class="error">E   AssertionError: &#x27;&#x27; != &#x27;1 Stop&#x27;</span><br/><span class="error">E   + 1 Stop</span><br/><span class="error">E   </span><br/><span class="error">E   -+ [28/35] +-</span><br/><span class="error">E   </span><br/><span class="error">E   +----------------------+----------------------+----------------------+</span><br/><span class="error">E    Failure 29 (&quot;wrapper&quot; method)</span><br/><span class="error">E   +----------------------+----------------------+----------------------+</span><br/><span class="error">E   Traceback (most recent call last):</span><br/><span class="error">E     File &quot;/Users/evgen/PycharmProjects/Selenium/utilitize/utils.py&quot;, line 8, in assert_item_in_list</span><br/><span class="error">E       self.soft_assert(self.assertEqual, stop.text, value)</span><br/><span class="error">E     File &quot;/Users/evgen/PycharmProjects/Selenium/testcases/test_case1.py&quot;, line 32, in test_search_trip</span><br/><span class="error">E       self.ut.assert_item_in_list(search_result.get_all_element_one_stop(), &quot;1 Stop&quot;)</span><br/><span class="error">E     File &quot;/Users/evgen/PycharmProjects/Selenium/venv/lib/python3.11/site-packages/ddt.py&quot;, line 220, in wrapper</span><br/><span class="error">E       return func(self, *args, **kwargs)</span><br/><span class="error">E     File &quot;/Users/evgen/PycharmProjects/Selenium/venv/lib/python3.11/site-packages/softest/case.py&quot;, line 62, in soft_assert</span><br/><span class="error">E       assert_method(*arguments, **keywords)</span><br/><span class="error">E     File &quot;/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py&quot;, line 873, in assertEqual</span><br/><span class="error">E       assertion_func(first, second, msg=msg)</span><br/><span class="error">E     File &quot;/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py&quot;, line 1253, in assertMultiLineEqual</span><br/><span class="error">E       self.fail(self._formatMessage(msg, standardMsg))</span><br/><span class="error">E     File &quot;/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py&quot;, line 703, in fail</span><br/><span class="error">E       raise self.failureException(msg)</span><br/><span class="error">E   AssertionError: &#x27;&#x27; != &#x27;1 Stop&#x27;</span><br/><span class="error">E   + 1 Stop</span><br/><span class="error">E   </span><br/><span class="error">E   -+ [29/35] +-</span><br/><span class="error">E   </span><br/><span class="error">E   +----------------------+----------------------+----------------------+</span><br/><span class="error">E    Failure 30 (&quot;wrapper&quot; method)</span><br/><span class="error">E   +----------------------+----------------------+----------------------+</span><br/><span class="error">E   Traceback (most recent call last):</span><br/><span class="error">E     File &quot;/Users/evgen/PycharmProjects/Selenium/utilitize/utils.py&quot;, line 8, in assert_item_in_list</span><br/><span class="error">E       self.soft_assert(self.assertEqual, stop.text, value)</span><br/><span class="error">E     File &quot;/Users/evgen/PycharmProjects/Selenium/testcases/test_case1.py&quot;, line 32, in test_search_trip</span><br/><span class="error">E       self.ut.assert_item_in_list(search_result.get_all_element_one_stop(), &quot;1 Stop&quot;)</span><br/><span class="error">E     File &quot;/Users/evgen/PycharmProjects/Selenium/venv/lib/python3.11/site-packages/ddt.py&quot;, line 220, in wrapper</span><br/><span class="error">E       return func(self, *args, **kwargs)</span><br/><span class="error">E     File &quot;/Users/evgen/PycharmProjects/Selenium/venv/lib/python3.11/site-packages/softest/case.py&quot;, line 62, in soft_assert</span><br/><span class="error">E       assert_method(*arguments, **keywords)</span><br/><span class="error">E     File &quot;/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py&quot;, line 873, in assertEqual</span><br/><span class="error">E       assertion_func(first, second, msg=msg)</span><br/><span class="error">E     File &quot;/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py&quot;, line 1253, in assertMultiLineEqual</span><br/><span class="error">E       self.fail(self._formatMessage(msg, standardMsg))</span><br/><span class="error">E     File &quot;/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py&quot;, line 703, in fail</span><br/><span class="error">E       raise self.failureException(msg)</span><br/><span class="error">E   AssertionError: &#x27;&#x27; != &#x27;1 Stop&#x27;</span><br/><span class="error">E   + 1 Stop</span><br/><span class="error">E   </span><br/><span class="error">E   -+ [30/35] +-</span><br/><span class="error">E   </span><br/><span class="error">E   +----------------------+----------------------+----------------------+</span><br/><span class="error">E    Failure 31 (&quot;wrapper&quot; method)</span><br/><span class="error">E   +----------------------+----------------------+----------------------+</span><br/><span class="error">E   Traceback (most recent call last):</span><br/><span class="error">E     File &quot;/Users/evgen/PycharmProjects/Selenium/utilitize/utils.py&quot;, line 8, in assert_item_in_list</span><br/><span class="error">E       self.soft_assert(self.assertEqual, stop.text, value)</span><br/><span class="error">E     File &quot;/Users/evgen/PycharmProjects/Selenium/testcases/test_case1.py&quot;, line 32, in test_search_trip</span><br/><span class="error">E       self.ut.assert_item_in_list(search_result.get_all_element_one_stop(), &quot;1 Stop&quot;)</span><br/><span class="error">E     File &quot;/Users/evgen/PycharmProjects/Selenium/venv/lib/python3.11/site-packages/ddt.py&quot;, line 220, in wrapper</span><br/><span class="error">E       return func(self, *args, **kwargs)</span><br/><span class="error">E     File &quot;/Users/evgen/PycharmProjects/Selenium/venv/lib/python3.11/site-packages/softest/case.py&quot;, line 62, in soft_assert</span><br/><span class="error">E       assert_method(*arguments, **keywords)</span><br/><span class="error">E     File &quot;/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py&quot;, line 873, in assertEqual</span><br/><span class="error">E       assertion_func(first, second, msg=msg)</span><br/><span class="error">E     File &quot;/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py&quot;, line 1253, in assertMultiLineEqual</span><br/><span class="error">E       self.fail(self._formatMessage(msg, standardMsg))</span><br/><span class="error">E     File &quot;/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py&quot;, line 703, in fail</span><br/><span class="error">E       raise self.failureException(msg)</span><br/><span class="error">E   AssertionError: &#x27;&#x27; != &#x27;1 Stop&#x27;</span><br/><span class="error">E   + 1 Stop</span><br/><span class="error">E   </span><br/><span class="error">E   -+ [31/35] +-</span><br/><span class="error">E   </span><br/><span class="error">E   +----------------------+----------------------+----------------------+</span><br/><span class="error">E    Failure 32 (&quot;wrapper&quot; method)</span><br/><span class="error">E   +----------------------+----------------------+----------------------+</span><br/><span class="error">E   Traceback (most recent call last):</span><br/><span class="error">E     File &quot;/Users/evgen/PycharmProjects/Selenium/utilitize/utils.py&quot;, line 8, in assert_item_in_list</span><br/><span class="error">E       self.soft_assert(self.assertEqual, stop.text, value)</span><br/><span class="error">E     File &quot;/Users/evgen/PycharmProjects/Selenium/testcases/test_case1.py&quot;, line 32, in test_search_trip</span><br/><span class="error">E       self.ut.assert_item_in_list(search_result.get_all_element_one_stop(), &quot;1 Stop&quot;)</span><br/><span class="error">E     File &quot;/Users/evgen/PycharmProjects/Selenium/venv/lib/python3.11/site-packages/ddt.py&quot;, line 220, in wrapper</span><br/><span class="error">E       return func(self, *args, **kwargs)</span><br/><span class="error">E     File &quot;/Users/evgen/PycharmProjects/Selenium/venv/lib/python3.11/site-packages/softest/case.py&quot;, line 62, in soft_assert</span><br/><span class="error">E       assert_method(*arguments, **keywords)</span><br/><span class="error">E     File &quot;/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py&quot;, line 873, in assertEqual</span><br/><span class="error">E       assertion_func(first, second, msg=msg)</span><br/><span class="error">E     File &quot;/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py&quot;, line 1253, in assertMultiLineEqual</span><br/><span class="error">E       self.fail(self._formatMessage(msg, standardMsg))</span><br/><span class="error">E     File &quot;/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py&quot;, line 703, in fail</span><br/><span class="error">E       raise self.failureException(msg)</span><br/><span class="error">E   AssertionError: &#x27;&#x27; != &#x27;1 Stop&#x27;</span><br/><span class="error">E   + 1 Stop</span><br/><span class="error">E   </span><br/><span class="error">E   -+ [32/35] +-</span><br/><span class="error">E   </span><br/><span class="error">E   +----------------------+----------------------+----------------------+</span><br/><span class="error">E    Failure 33 (&quot;wrapper&quot; method)</span><br/><span class="error">E   +----------------------+----------------------+----------------------+</span><br/><span class="error">E   Traceback (most recent call last):</span><br/><span class="error">E     File &quot;/Users/evgen/PycharmProjects/Selenium/utilitize/utils.py&quot;, line 8, in assert_item_in_list</span><br/><span class="error">E       self.soft_assert(self.assertEqual, stop.text, value)</span><br/><span class="error">E     File &quot;/Users/evgen/PycharmProjects/Selenium/testcases/test_case1.py&quot;, line 32, in test_search_trip</span><br/><span class="error">E       self.ut.assert_item_in_list(search_result.get_all_element_one_stop(), &quot;1 Stop&quot;)</span><br/><span class="error">E     File &quot;/Users/evgen/PycharmProjects/Selenium/venv/lib/python3.11/site-packages/ddt.py&quot;, line 220, in wrapper</span><br/><span class="error">E       return func(self, *args, **kwargs)</span><br/><span class="error">E     File &quot;/Users/evgen/PycharmProjects/Selenium/venv/lib/python3.11/site-packages/softest/case.py&quot;, line 62, in soft_assert</span><br/><span class="error">E       assert_method(*arguments, **keywords)</span><br/><span class="error">E     File &quot;/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py&quot;, line 873, in assertEqual</span><br/><span class="error">E       assertion_func(first, second, msg=msg)</span><br/><span class="error">E     File &quot;/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py&quot;, line 1253, in assertMultiLineEqual</span><br/><span class="error">E       self.fail(self._formatMessage(msg, standardMsg))</span><br/><span class="error">E     File &quot;/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py&quot;, line 703, in fail</span><br/><span class="error">E       raise self.failureException(msg)</span><br/><span class="error">E   AssertionError: &#x27;&#x27; != &#x27;1 Stop&#x27;</span><br/><span class="error">E   + 1 Stop</span><br/><span class="error">E   </span><br/><span class="error">E   -+ [33/35] +-</span><br/><span class="error">E   </span><br/><span class="error">E   +----------------------+----------------------+----------------------+</span><br/><span class="error">E    Failure 34 (&quot;wrapper&quot; method)</span><br/><span class="error">E   +----------------------+----------------------+----------------------+</span><br/><span class="error">E   Traceback (most recent call last):</span><br/><span class="error">E     File &quot;/Users/evgen/PycharmProjects/Selenium/utilitize/utils.py&quot;, line 8, in assert_item_in_list</span><br/><span class="error">E       self.soft_assert(self.assertEqual, stop.text, value)</span><br/><span class="error">E     File &quot;/Users/evgen/PycharmProjects/Selenium/testcases/test_case1.py&quot;, line 32, in test_search_trip</span><br/><span class="error">E       self.ut.assert_item_in_list(search_result.get_all_element_one_stop(), &quot;1 Stop&quot;)</span><br/><span class="error">E     File &quot;/Users/evgen/PycharmProjects/Selenium/venv/lib/python3.11/site-packages/ddt.py&quot;, line 220, in wrapper</span><br/><span class="error">E       return func(self, *args, **kwargs)</span><br/><span class="error">E     File &quot;/Users/evgen/PycharmProjects/Selenium/venv/lib/python3.11/site-packages/softest/case.py&quot;, line 62, in soft_assert</span><br/><span class="error">E       assert_method(*arguments, **keywords)</span><br/><span class="error">E     File &quot;/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py&quot;, line 873, in assertEqual</span><br/><span class="error">E       assertion_func(first, second, msg=msg)</span><br/><span class="error">E     File &quot;/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py&quot;, line 1253, in assertMultiLineEqual</span><br/><span class="error">E       self.fail(self._formatMessage(msg, standardMsg))</span><br/><span class="error">E     File &quot;/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py&quot;, line 703, in fail</span><br/><span class="error">E       raise self.failureException(msg)</span><br/><span class="error">E   AssertionError: &#x27;&#x27; != &#x27;1 Stop&#x27;</span><br/><span class="error">E   + 1 Stop</span><br/><span class="error">E   </span><br/><span class="error">E   -+ [34/35] +-</span><br/><span class="error">E   </span><br/><span class="error">E   +----------------------+----------------------+----------------------+</span><br/><span class="error">E    Failure 35 (&quot;wrapper&quot; method)</span><br/><span class="error">E   +----------------------+----------------------+----------------------+</span><br/><span class="error">E   Traceback (most recent call last):</span><br/><span class="error">E     File &quot;/Users/evgen/PycharmProjects/Selenium/utilitize/utils.py&quot;, line 8, in assert_item_in_list</span><br/><span class="error">E       self.soft_assert(self.assertEqual, stop.text, value)</span><br/><span class="error">E     File &quot;/Users/evgen/PycharmProjects/Selenium/testcases/test_case1.py&quot;, line 32, in test_search_trip</span><br/><span class="error">E       self.ut.assert_item_in_list(search_result.get_all_element_one_stop(), &quot;1 Stop&quot;)</span><br/><span class="error">E     File &quot;/Users/evgen/PycharmProjects/Selenium/venv/lib/python3.11/site-packages/ddt.py&quot;, line 220, in wrapper</span><br/><span class="error">E       return func(self, *args, **kwargs)</span><br/><span class="error">E     File &quot;/Users/evgen/PycharmProjects/Selenium/venv/lib/python3.11/site-packages/softest/case.py&quot;, line 62, in soft_assert</span><br/><span class="error">E       assert_method(*arguments, **keywords)</span><br/><span class="error">E     File &quot;/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py&quot;, line 873, in assertEqual</span><br/><span class="error">E       assertion_func(first, second, msg=msg)</span><br/><span class="error">E     File &quot;/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py&quot;, line 1253, in assertMultiLineEqual</span><br/><span class="error">E       self.fail(self._formatMessage(msg, standardMsg))</span><br/><span class="error">E     File &quot;/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py&quot;, line 703, in fail</span><br/><span class="error">E       raise self.failureException(msg)</span><br/><span class="error">E   AssertionError: &#x27;&#x27; != &#x27;1 Stop&#x27;</span><br/><span class="error">E   + 1 Stop</span><br/><span class="error">E   </span><br/><span class="error">E   -+ [35/35] +-</span><br/> ------------------------------Captured stdout call------------------------------ <br/>Text is 1 Stop
passed
Text is 1 Stop
passed
Text is 1 Stop
passed
Text is 1 Stop
passed
Text is 1 Stop
passed
Text is 1 Stop
passed
Text is 1 Stop
passed
Text is 
failed
Text is 1 Stop
passed
Text is 1 Stop
passed
Text is 1 Stop
passed
Text is 1 Stop
passed
Text is 1 Stop
passed
Text is 1 Stop
passed
Text is 1 Stop
passed
Text is 1 Stop
passed
Text is 
failed
Text is 1 Stop
passed
Text is 1 Stop
passed
Text is 1 Stop
passed
Text is 1 Stop
passed
Text is 1 Stop
passed
Text is 1 Stop
passed
Text is 1 Stop
passed
Text is 1 Stop
passed
Text is 1 Stop
passed
Text is 
failed
Text is 
failed
Text is 
failed
Text is 1 Stop
passed
Text is 
failed
Text is 1 Stop
passed
Text is 
failed
Text is 
failed
Text is 
failed
Text is 
failed
Text is 
failed
Text is 1 Stop
passed
Text is 
failed
Text is 
failed
Text is 
failed
Text is 1 Stop
passed
Text is 
failed
Text is 1 Stop
passed
Text is 1 Stop
passed
Text is 1 Stop
passed
Text is 1 Stop
passed
Text is 1 Stop
passed
Text is 1 Stop
passed
Text is 1 Stop
passed
Text is 
failed
Text is 1 Stop
passed
Text is 1 Stop
passed
Text is 1 Stop
passed
Text is 
failed
Text is 
failed
Text is 1 Stop
passed
Text is 
failed
Text is 1 Stop
passed
Text is 1 Stop
passed
Text is 1 Stop
passed
Text is 1 Stop
passed
Text is 1 Stop
passed
Text is 1 Stop
passed
Text is 
failed
Text is 1 Stop
passed
Text is 1 Stop
passed
Text is 1 Stop
passed
Text is 
failed
Text is 1 Stop
passed
Text is 
failed
Text is 1 Stop
passed
Text is 1 Stop
passed
Text is 
failed
Text is 
failed
Text is 
failed
Text is 1 Stop
passed
Text is 1 Stop
passed
Text is 
failed
Text is 
failed
Text is 
failed
Text is 1 Stop
passed
Text is 
failed
Text is 1 Stop
passed
Text is 
failed
Text is 
failed
Text is 1 Stop
passed
Text is 
failed
Text is 
failed
Text is 
failed
Text is 
failed
Text is 1 Stop
passed
Text is 1 Stop
passed
<br/> -------------------------------Captured log call-------------------------------- <br/>INFO     logger:launch_page_yatro.py:46 Clicked on location from
INFO     logger:launch_page_yatro.py:54 Clicked on location to
INFO     logger:launch_page_yatro.py:66 Pick up the date
INFO     logger:test_case1.py:31 Select 1 Stop<br/></div></td></tr></tbody>
      <tbody class="failed results-table-row">
        <tr>
          <td class="col-result">Failed</td>
          <td class="col-name">testcases/test_case1.py::TestOne::test_search_trip_2_test2</td>
          <td class="col-duration">23.59</td>
          <td class="col-links"><a class="url" href="https://www.yatra.com/" target="_blank">URL</a> </td></tr>
        <tr>
          <td class="extra" colspan="4">
            <div><div><img src="testcases/test_case1.py_TestOne_test_search_trip_2_test2.png" alt="screenshot" style="width:300px;height=200px"onclick="window.open(this.src)" align="right"/></div></div>
            <div class="log">self = &lt;testcases.test_case1.TestOne testMethod=test_search_trip_2_test2&gt;, going_from = &#x27;BOM&#x27;, going_to = &#x27;MEL&#x27;, auto_going_to = &#x27;MEL&#x27;, date = &#x27;25/01/2023&#x27;<br/><br/>    @file_data(&quot;/Users/evgen/PycharmProjects/Selenium/testdata/testdata.json&quot;)<br/>    def test_search_trip(self, going_from, going_to, auto_going_to, date):<br/>        search_result = self.l.search_flights(going_from, going_to, auto_going_to, date)<br/>        time.sleep(2)<br/>        self.l.page_scroll()<br/>        time.sleep(3)<br/>&gt;       search_result.click_filter_flights()<br/><br/>testcases/test_case1.py:30: <br/>_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ <br/>page/search_results_page.py:21: in click_filter_flights<br/>    self.get_filter_flights().click()<br/>venv/lib/python3.11/site-packages/selenium/webdriver/remote/webelement.py:93: in click<br/>    self._execute(Command.CLICK_ELEMENT)<br/>venv/lib/python3.11/site-packages/selenium/webdriver/remote/webelement.py:410: in _execute<br/>    return self._parent.execute(command, params)<br/>venv/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py:444: in execute<br/>    self.error_handler.check_response(response)<br/>_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ <br/><br/>self = &lt;selenium.webdriver.remote.errorhandler.ErrorHandler object at 0x10b5b5ad0&gt;<br/>response = {&#x27;status&#x27;: 400, &#x27;value&#x27;: &#x27;{&quot;value&quot;:{&quot;error&quot;:&quot;element click intercepted&quot;,&quot;message&quot;:&quot;element click intercepted: Element ...fff6ca68109 _pthread_start + 148\\n24  libsystem_pthread.dylib             0x00007fff6ca63b8b thread_start + 15\\n&quot;}}&#x27;}<br/><br/>    def check_response(self, response: Dict[str, Any]) -&gt; None:<br/>        &quot;&quot;&quot;<br/>        Checks that a JSON response from the WebDriver does not have an error.<br/>    <br/>        :Args:<br/>         - response - The JSON response from the WebDriver server as a dictionary<br/>           object.<br/>    <br/>        :Raises: If the response contains an error message.<br/>        &quot;&quot;&quot;<br/>        status = response.get(&quot;status&quot;, None)<br/>        if not status or status == ErrorCode.SUCCESS:<br/>            return<br/>        value = None<br/>        message = response.get(&quot;message&quot;, &quot;&quot;)<br/>        screen: str = response.get(&quot;screen&quot;, &quot;&quot;)<br/>        stacktrace = None<br/>        if isinstance(status, int):<br/>            value_json = response.get(&quot;value&quot;, None)<br/>            if value_json and isinstance(value_json, str):<br/>                import json<br/>    <br/>                try:<br/>                    value = json.loads(value_json)<br/>                    if len(value.keys()) == 1:<br/>                        value = value[&quot;value&quot;]<br/>                    status = value.get(&quot;error&quot;, None)<br/>                    if not status:<br/>                        status = value.get(&quot;status&quot;, ErrorCode.UNKNOWN_ERROR)<br/>                        message = value.get(&quot;value&quot;) or value.get(&quot;message&quot;)<br/>                        if not isinstance(message, str):<br/>                            value = message<br/>                            message = message.get(&quot;message&quot;)<br/>                    else:<br/>                        message = value.get(&quot;message&quot;, None)<br/>                except ValueError:<br/>                    pass<br/>    <br/>        exception_class: Type[WebDriverException]<br/>        if status in ErrorCode.NO_SUCH_ELEMENT:<br/>            exception_class = NoSuchElementException<br/>        elif status in ErrorCode.NO_SUCH_FRAME:<br/>            exception_class = NoSuchFrameException<br/>        elif status in ErrorCode.NO_SUCH_SHADOW_ROOT:<br/>            exception_class = NoSuchShadowRootException<br/>        elif status in ErrorCode.NO_SUCH_WINDOW:<br/>            exception_class = NoSuchWindowException<br/>        elif status in ErrorCode.STALE_ELEMENT_REFERENCE:<br/>            exception_class = StaleElementReferenceException<br/>        elif status in ErrorCode.ELEMENT_NOT_VISIBLE:<br/>            exception_class = ElementNotVisibleException<br/>        elif status in ErrorCode.INVALID_ELEMENT_STATE:<br/>            exception_class = InvalidElementStateException<br/>        elif (<br/>            status in ErrorCode.INVALID_SELECTOR<br/>            or status in ErrorCode.INVALID_XPATH_SELECTOR<br/>            or status in ErrorCode.INVALID_XPATH_SELECTOR_RETURN_TYPER<br/>        ):<br/>            exception_class = InvalidSelectorException<br/>        elif status in ErrorCode.ELEMENT_IS_NOT_SELECTABLE:<br/>            exception_class = ElementNotSelectableException<br/>        elif status in ErrorCode.ELEMENT_NOT_INTERACTABLE:<br/>            exception_class = ElementNotInteractableException<br/>        elif status in ErrorCode.INVALID_COOKIE_DOMAIN:<br/>            exception_class = InvalidCookieDomainException<br/>        elif status in ErrorCode.UNABLE_TO_SET_COOKIE:<br/>            exception_class = UnableToSetCookieException<br/>        elif status in ErrorCode.TIMEOUT:<br/>            exception_class = TimeoutException<br/>        elif status in ErrorCode.SCRIPT_TIMEOUT:<br/>            exception_class = TimeoutException<br/>        elif status in ErrorCode.UNKNOWN_ERROR:<br/>            exception_class = WebDriverException<br/>        elif status in ErrorCode.UNEXPECTED_ALERT_OPEN:<br/>            exception_class = UnexpectedAlertPresentException<br/>        elif status in ErrorCode.NO_ALERT_OPEN:<br/>            exception_class = NoAlertPresentException<br/>        elif status in ErrorCode.IME_NOT_AVAILABLE:<br/>            exception_class = ImeNotAvailableException<br/>        elif status in ErrorCode.IME_ENGINE_ACTIVATION_FAILED:<br/>            exception_class = ImeActivationFailedException<br/>        elif status in ErrorCode.MOVE_TARGET_OUT_OF_BOUNDS:<br/>            exception_class = MoveTargetOutOfBoundsException<br/>        elif status in ErrorCode.JAVASCRIPT_ERROR:<br/>            exception_class = JavascriptException<br/>        elif status in ErrorCode.SESSION_NOT_CREATED:<br/>            exception_class = SessionNotCreatedException<br/>        elif status in ErrorCode.INVALID_ARGUMENT:<br/>            exception_class = InvalidArgumentException<br/>        elif status in ErrorCode.NO_SUCH_COOKIE:<br/>            exception_class = NoSuchCookieException<br/>        elif status in ErrorCode.UNABLE_TO_CAPTURE_SCREEN:<br/>            exception_class = ScreenshotException<br/>        elif status in ErrorCode.ELEMENT_CLICK_INTERCEPTED:<br/>            exception_class = ElementClickInterceptedException<br/>        elif status in ErrorCode.INSECURE_CERTIFICATE:<br/>            exception_class = InsecureCertificateException<br/>        elif status in ErrorCode.INVALID_COORDINATES:<br/>            exception_class = InvalidCoordinatesException<br/>        elif status in ErrorCode.INVALID_SESSION_ID:<br/>            exception_class = InvalidSessionIdException<br/>        elif status in ErrorCode.UNKNOWN_METHOD:<br/>            exception_class = UnknownMethodException<br/>        else:<br/>            exception_class = WebDriverException<br/>        if not value:<br/>            value = response[&quot;value&quot;]<br/>        if isinstance(value, str):<br/>            raise exception_class(value)<br/>        if message == &quot;&quot; and &quot;message&quot; in value:<br/>            message = value[&quot;message&quot;]<br/>    <br/>        screen = None  # type: ignore[assignment]<br/>        if &quot;screen&quot; in value:<br/>            screen = value[&quot;screen&quot;]<br/>    <br/>        stacktrace = None<br/>        st_value = value.get(&quot;stackTrace&quot;) or value.get(&quot;stacktrace&quot;)<br/>        if st_value:<br/>            if isinstance(st_value, str):<br/>                stacktrace = st_value.split(&quot;\n&quot;)<br/>            else:<br/>                stacktrace = []<br/>                try:<br/>                    for frame in st_value:<br/>                        line = frame.get(&quot;lineNumber&quot;, &quot;&quot;)<br/>                        file = frame.get(&quot;fileName&quot;, &quot;&lt;anonymous&gt;&quot;)<br/>                        if line:<br/>                            file = f&quot;{file}:{line}&quot;<br/>                        meth = frame.get(&quot;methodName&quot;, &quot;&lt;anonymous&gt;&quot;)<br/>                        if &quot;className&quot; in frame:<br/>                            meth = &quot;{}.{}&quot;.format(frame[&quot;className&quot;], meth)<br/>                        msg = &quot;    at %s (%s)&quot;<br/>                        msg = msg % (meth, file)<br/>                        stacktrace.append(msg)<br/>                except TypeError:<br/>                    pass<br/>        if exception_class == UnexpectedAlertPresentException:<br/>            alert_text = None<br/>            if &quot;data&quot; in value:<br/>                alert_text = value[&quot;data&quot;].get(&quot;text&quot;)<br/>            elif &quot;alert&quot; in value:<br/>                alert_text = value[&quot;alert&quot;].get(&quot;text&quot;)<br/>            raise exception_class(message, screen, stacktrace, alert_text)  # type: ignore[call-arg]  # mypy is not smart enough here<br/>&gt;       raise exception_class(message, screen, stacktrace)<br/><span class="error">E       selenium.common.exceptions.ElementClickInterceptedException: Message: element click intercepted: Element is not clickable at point (494, -1634)</span><br/><span class="error">E         (Session info: chrome=109.0.5414.87)</span><br/><span class="error">E       Stacktrace:</span><br/><span class="error">E       0   chromedriver                        0x000000010ef1cfa8 chromedriver + 4886440</span><br/><span class="error">E       1   chromedriver                        0x000000010ee9a643 chromedriver + 4351555</span><br/><span class="error">E       2   chromedriver                        0x000000010eae8b27 chromedriver + 477991</span><br/><span class="error">E       3   chromedriver                        0x000000010eb36a78 chromedriver + 797304</span><br/><span class="error">E       4   chromedriver                        0x000000010eb33e7c chromedriver + 786044</span><br/><span class="error">E       5   chromedriver                        0x000000010eb30a94 chromedriver + 772756</span><br/><span class="error">E       6   chromedriver                        0x000000010eb2f5ab chromedriver + 767403</span><br/><span class="error">E       7   chromedriver                        0x000000010eb1fd73 chromedriver + 703859</span><br/><span class="error">E       8   chromedriver                        0x000000010eb535d2 chromedriver + 914898</span><br/><span class="error">E       9   chromedriver                        0x000000010eb1f3dd chromedriver + 701405</span><br/><span class="error">E       10  chromedriver                        0x000000010eb5378e chromedriver + 915342</span><br/><span class="error">E       11  chromedriver                        0x000000010eb6e5fe chromedriver + 1025534</span><br/><span class="error">E       12  chromedriver                        0x000000010eb533a3 chromedriver + 914339</span><br/><span class="error">E       13  chromedriver                        0x000000010eb1d57f chromedriver + 693631</span><br/><span class="error">E       14  chromedriver                        0x000000010eb1eb1e chromedriver + 699166</span><br/><span class="error">E       15  chromedriver                        0x000000010eee9b9e chromedriver + 4676510</span><br/><span class="error">E       16  chromedriver                        0x000000010eeee91e chromedriver + 4696350</span><br/><span class="error">E       17  chromedriver                        0x000000010eef619f chromedriver + 4727199</span><br/><span class="error">E       18  chromedriver                        0x000000010eeef81a chromedriver + 4700186</span><br/><span class="error">E       19  chromedriver                        0x000000010eec2a62 chromedriver + 4516450</span><br/><span class="error">E       20  chromedriver                        0x000000010ef0e8c8 chromedriver + 4827336</span><br/><span class="error">E       21  chromedriver                        0x000000010ef0ea45 chromedriver + 4827717</span><br/><span class="error">E       22  chromedriver                        0x000000010ef247ef chromedriver + 4917231</span><br/><span class="error">E       23  libsystem_pthread.dylib             0x00007fff6ca68109 _pthread_start + 148</span><br/><span class="error">E       24  libsystem_pthread.dylib             0x00007fff6ca63b8b thread_start + 15</span><br/><br/>venv/lib/python3.11/site-packages/selenium/webdriver/remote/errorhandler.py:249: ElementClickInterceptedException<br/> -------------------------------Captured log call-------------------------------- <br/>INFO     logger:launch_page_yatro.py:46 Clicked on location from
INFO     logger:launch_page_yatro.py:54 Clicked on location to
INFO     logger:launch_page_yatro.py:66 Pick up the date<br/></div></td></tr></tbody></table></body></html>